version: "3.0"
services:
  mysql:
    network_mode: "bridge"
    container_name: mysql
    image: "mysql:5.7"

    volumes:
    - "./mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: "spring"
      MYSQL_PASSWORD: "654321"
      MYSQL_DATABASE: "bot"
    ports:
    - "3306:3306"